### ISSUE TITLE
DB loan DAO/DTO 클래스

### ISSUE THREAD

**Issue by Yang-Seungmo** [ohsoou/LibrarySystem#17]
DB loan table DAO/DTO 클래스 생성

**Comment by ohsoou** [comment]
1. auto close로 바꾸고 다른 사람 코드보면서 코드 통일성 맞추기
2. 62번째줄 제네릭
3. update문 -> 반납해서 returndate 입력/ 연장해서 extend 입력
4. insert할때 loan num 시퀀스 값으로 들어가야함
